[allowlist]
description = "Global Allowlist"

# Ignore based on any subset of the file path
paths = [
    '''test/unit/authentication/by_password_test.rb''',
    '''test/integration/admin/api/buyers_users_controller_test.rb'''
]
