base: &default
  superdomain: <%= superdomain = ENV.fetch('THREESCALE_SUPERDOMAIN', 'example.com') %>
  dev_domain: <%= ENV['THREESCALE_DEV_DOMAIN'] == '1' %>
  apicast_internal_host_regexp: '\Asystem-(.*)\Z'
  secure_cookie: <%= ENV.fetch('FORCE_SSL', '1') == '1' %>
  force_ssl: <%= ENV.fetch('FORCE_SSL', '1') == '1' %>
  apicast_oauth: <%= ENV.fetch('ENABLE_APICAST_OAUTH', '0') == '1' %>
  apicast_custom_url: <%= ENV.fetch('ENABLE_APICAST_CUSTOM_URL', '0') == '1' %>
  active_docs_url: <%= ENV.fetch('ACTIVE_DOCS_URL', "https://support-staging.#{superdomain}") %>
  active_docs_proxy_disabled: true
  asset_host: <%= ENV.fetch('RAILS_ASSET_HOST', nil) %>
  daily_weekly_reports_pref: <%= ENV.fetch('ENABLE_DAILY_WEEKLY_REPORTS_PREF', '1') == '1' %>
  readonly_custom_domains_settings: <%= ENV.fetch('READONLY_CUSTOM_DOMAINS_SETTINGS', '1') == '1' %>
  airbrake_api_key: <%= ENV['AIRBRAKE_API_KEY'] %>
  bugsnag_api_key: <%= ENV['BUGSNAG_API_KEY'] %>
  events_shared_secret: <%= ENV['EVENTS_SHARED_SECRET'] %>
  recaptcha_public_key: <%= ENV.fetch('RECAPTCHA_PUBLIC_KEY', 'YOUR_RECAPTCHA_PUBLIC_KEY') %>
  recaptcha_private_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
  impersonation_admin:
    username: <%= ENV.fetch('IMPERSONATION_ADMIN_USERNAME', '3scaleadmin') %>
    domain: <%= ENV.fetch('IMPERSONATION_ADMIN_DOMAIN', '3scale.net') %>

  # System Emails
  noreply_email: <%= ENV.fetch('NOREPLY_EMAIL', "no-reply@#{superdomain}") %>
  support_email: <%= ENV.fetch('SUPPORT_EMAIL', "#{superdomain} Support <support@#{superdomain}>") %>
  sales_email: <%= ENV.fetch('SALES_EMAIL', "sales@#{superdomain}") %>
  notification_email: <%= ENV.fetch('NOTIFICATION_EMAIL', "#{superdomain} Notification <no-reply@#{superdomain}>") %>
  golive_email: <%= ENV.fetch('GOLIVE_EMAIL', "golive@#{superdomain}") %>
  sysadmin_email: <%= ENV.fetch('SYSADMIN_EMAIL', "sysadmin@#{superdomain}") %>

  report_traffic: false
  hide_basic_switches: true
  tenant_mode: <%= ENV.fetch('TENANT_MODE', 'multitenant') %>
  db_secret: <%= ENV.fetch('DB_SECRET', SecureRandom.hex(20)) %>
  onpremises_api_docs_version: true
  assets_cdn_host: <%= ENV.fetch('ASSETS_CDN_HOST', '') %>
  email_sanitizer:
    enabled: <%= ENV.fetch('EMAIL_SANITIZER_ENABLED', Rails.env.preview?) %>
    to: <%= ENV.fetch('EMAIL_SANITIZER_TO', 'sanitizer@example.com') %>
  onpremises: true
  dev_gtld: <%= ENV.fetch('DEV_GTLD', 'localhost') %>
  active_merchant_logging: <%= ENV.fetch('ACTIVE_MERCHANT_LOGGING', false) %>
  billing_canaries:
  apicast_staging_url: <%= ENV.fetch('APICAST_STAGING_URL', 'apicast-staging:8090') %>
  zync_authentication_token: <%= ENV.fetch('ZYNC_AUTHENTICATON_TOKEN', '') %>

development:
  <<: *default

test:
  <<: *default

preview:
  <<: *default

production:
  <<: *default
