production:
  url: <%= ENV.fetch('BACKEND_ROUTE', 'http://backend-listener:3000/internal/') %>
  fake_server: false
  username: <%= ENV.fetch('CONFIG_INTERNAL_API_USER', nil) %>
  password: <%= ENV.fetch('CONFIG_INTERNAL_API_PASSWORD', nil) %>
