production:
  'USD - American Dollar': 'USD'
  'EUR - Euro': 'EUR'
  'GBP - British Pound': 'GBP'
  'NZD - New Zealand dollar': 'NZD'
  'CNY - Chinese Yuan Renminbi': 'CNY'
  'CAD - Canadian Dollar': 'CAD'
  'AUD - Australian Dollar': 'AUD'
  'JPY - Japanese Yen': 'JPY'
  'CHF - Swiss Franc': 'CHF'
  'SAR - Saudi Riyal': 'SAR'
