base: &default
  new_provider_documentation: false
  proxy_pro: false
  instant_bill_plan_change: false
  service_permissions: true
  async_apicast_deploy: false
  duplicate_application_id: true
  duplicate_user_key: true
  plan_changes_wizard: false
  require_cc_on_signup: false
  apicast_per_service: true
  new_notification_system: true
  cms_api: false
  apicast_v2: true
  forum: false
  published_service_plan_signup: true
  policies: true

production:
  <<: *default

preview:
  <<: *default
