features: &default
  account_deletion:
    enabled: false
    account_inactivity: 365
    account_suspension: 90
    contract_unpaid_time: 183
    disabled_for_app_plans:
    - '%enterprise%'
  segment_deletion:
    enabled: false
    token: example-token
    root_uri: https://platform.segmentapis.com/v1beta
    workspace: example-workspace
    api: regulations
    request_size: 2000
    wait_time: 0
  logging:
    audits_to_stdout: true
  quickstarts:
    enabled: false
  email_configuration:
    enabled: false

development:
  <<: *default

test:
  <<: *default

production:

preview:
