base: &default
  access_code: <%= ENV.fetch('ACCESS_CODE', '') %>
  active_docs_proxy_disabled: false
  apicast_custom_url: <%= ENV.fetch('ENABLE_APICAST_CUSTOM_URL', '0') == '1' %>
  asset_host: <%= ENV.fetch('RAILS_ASSET_HOST', nil) %>
  bugsnag_api_key: <%= ENV['BUGSNAG_API_KEY'] %>
  bugsnag_release_stage: <%= ENV.fetch('BUGSNAG_RELEASE_STAGE', Rails.env) %>
  daily_weekly_reports_pref: <%= ENV.fetch('ENABLE_DAILY_WEEKLY_REPORTS_PREF', '1') == '1' %>
  email_sanitizer:
    enabled: <%= ENV.fetch('EMAIL_SANITIZER_ENABLED', '0') == '1' %>
    to: <%= ENV.fetch('EMAIL_SANITIZER_TO', 'sanitizer@example.com') %>
  error_reporting_stages: <%= ENV.fetch('ERROR_REPORTING_STAGES', 'production') %>
  events_shared_secret: <%= ENV['EVENTS_SHARED_SECRET'] %>
  force_ssl: <%= ENV.fetch('FORCE_SSL', '1') == '1' %>
  hide_basic_switches: false
  impersonation_admin:
    domain: <%= ENV.fetch('IMPERSONATION_ADMIN_DOMAIN', '3scale.net') %>
    username: <%= ENV.fetch('IMPERSONATION_ADMIN_USERNAME', '3scaleadmin') %>
  janitor_worker_enabled: true
  onpremises: false
  onpremises_api_docs_version: false
  readonly_custom_domains_settings: <%= ENV.fetch('READONLY_CUSTOM_DOMAINS_SETTINGS', '0') == '1' %>
  recaptcha_private_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
  recaptcha_public_key: <%= ENV.fetch('RECAPTCHA_PUBLIC_KEY', 'YOUR_RECAPTCHA_PUBLIC_KEY') %>
  recaptcha_project_id: <%= ENV.fetch('RECAPTCHA_PROJECT_ID', nil) %>
  recaptcha_min_bot_score: <%= ENV.fetch('RECAPTCHA_MIN_BOT_SCORE', '0.5') %>
  report_traffic: false
  secure_cookie: <%= ENV.fetch('FORCE_SSL', '1') == '1' %>
  superdomain: <%= superdomain = ENV.fetch('THREESCALE_SUPERDOMAIN', 'example.com') %>
  tenant_mode: <%= ENV.fetch('TENANT_MODE', 'multitenant') %>
  user_session_ttl: <%= ENV.fetch('USER_SESSION_TTL', 2.weeks) %>
  zync_authentication_token: <%= ENV.fetch('ZYNC_AUTHENTICATION_TOKEN', '') %>

  ## defaults to 'default'
  # bulk_indexing_queue: bulk_indexing

  # apicast_internal_host_regexp:

  # System Emails
  noreply_email: <%= ENV.fetch('NOREPLY_EMAIL', "no-reply@#{superdomain}") %>
  notification_email: <%= ENV.fetch('NOTIFICATION_EMAIL', "#{superdomain} Notification <no-reply@#{superdomain}>") %>
  sales_email: <%= ENV.fetch('SALES_EMAIL', "sales@#{superdomain}") %>
  support_email: <%= ENV.fetch('SUPPORT_EMAIL', "#{superdomain} Support <support@#{superdomain}>") %>
  sysadmin_email: <%= ENV.fetch('SYSADMIN_EMAIL', "sysadmin@#{superdomain}") %>

  # deprecated: use payments.yaml to configure payments instead
  active_merchant_logging: <%= ENV.fetch('ACTIVE_MERCHANT_LOGGING', false) %>
  billing_canaries:

development:
  <<: *default
  active_merchant_logging: true
  force_ssl: false
  report_traffic: false
  secure_cookie: false
  strong_passwords_disabled: true

test:
  <<: *default
  force_ssl: false
  janitor_worker_enabled: false
  readonly_custom_domains_settings: true
  report_traffic: false
  secure_cookie: false

production:
  <<: *default
  active_docs_proxy_disabled: true
  active_merchant_logging: false
  apicast_custom_url: true
  apicast_internal_host_regexp: '\Asystem-(master|provider|developer)\Z'
  daily_weekly_reports_pref: false
  force_ssl: true
  hide_basic_switches: true
  janitor_worker_enabled: true ## same
  onpremises: true
  onpremises_api_docs_version: true
  readonly_custom_domains_settings: false
  secure_cookie: true
  tenant_mode: <%= ENV['TENANT_MODE'] %>
